#!/usr/bin/env python3
"""Regenerate assets/js/activity.js from Nehal's real GitHub contribution graph.

Reads the public contributions fragment GitHub renders for a profile, so it
needs no token and no API key. Run by .github/workflows/update-activity.yml
every night, and safe to run by hand:  python3 scripts/update_activity.py
"""
import json, re, sys, urllib.request, datetime, pathlib

USER = "NEHAL-S-DEVLR"
OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "js" / "activity.js"
UA = {"User-Agent": "Mozilla/5.0 (portfolio activity updater)"}


def get(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30) as r:
        return r.read().decode("utf-8", "replace")


def main():
    html = get(f"https://github.com/users/{USER}/contributions")

    cells = re.findall(r'<td[^>]*data-date="(\d{4}-\d{2}-\d{2})"[^>]*data-level="(\d)"[^>]*>', html)
    if not cells:
        cells = [(d, l) for l, d in
                 re.findall(r'data-level="(\d)"[^>]*data-date="(\d{4}-\d{2}-\d{2})"', html)]
    if len(cells) < 300:
        sys.exit(f"only found {len(cells)} day cells — GitHub markup may have changed")
    cells.sort()

    # per-day counts live in <tool-tip> elements keyed to each cell's id
    ids = dict(zip(
        re.findall(r'<td[^>]*data-date="(\d{4}-\d{2}-\d{2})"[^>]*id="([^"]+)"', html) or [],
        [None]))
    by_id = {}
    for cid, text in re.findall(r'<tool-tip[^>]*for="([^"]+)"[^>]*>([^<]*)</tool-tip>', html):
        m = re.match(r'\s*(No|\d+)\s+contribution', text)
        if m:
            by_id[cid] = 0 if m.group(1) == "No" else int(m.group(1))
    date_of_id = dict(re.findall(r'<td[^>]*data-date="(\d{4}-\d{2}-\d{2})"[^>]*id="([^"]+)"', html))
    count_for_date = {d: by_id[i] for d, i in date_of_id.items() if i in by_id}

    levels = "".join(l for _, l in cells)
    counts = [count_for_date.get(d, 0) for d, _ in cells]
    have_counts = any(counts)

    total = sum(counts) if have_counts else None
    if total is None:
        m = re.search(r"([\d,]+)\s*contributions", html)
        total = int(m.group(1).replace(",", "")) if m else sum(1 for l in levels if l != "0")

    active = sum(1 for l in levels if l != "0")
    best = run = 0
    for l in levels:
        run = run + 1 if l != "0" else 0
        best = max(best, run)

    repos = None
    try:
        repos = json.loads(get(f"https://api.github.com/users/{USER}")).get("public_repos")
    except Exception:
        pass

    data = {
        "start": cells[0][0],
        "end": cells[-1][0],
        "levels": levels,
        "counts": counts if have_counts else None,
        "total": total,
        "activeDays": active,
        "longestStreak": best,
        "repos": repos,
        "updated": datetime.date.today().isoformat(),
    }
    OUT.write_text(
        "/* Generated by scripts/update_activity.py — do not edit by hand.\n"
        "   Refreshed nightly by .github/workflows/update-activity.yml */\n"
        "window.ACTIVITY = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT.name}: {total} contributions, {active} active days, "
          f"streak {best}, repos {repos}, {cells[0][0]} → {cells[-1][0]}")


if __name__ == "__main__":
    main()
